CREATE DATABASE IF NOT EXISTS green_durham_grass_and_herb;
USE green_durham_grass_and_herb;

CREATE TABLE IF NOT EXISTS ethical (
    id INT AUTO_INCREMENT PRIMARY KEY,
    concern VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS labor (
    id INT AUTO_INCREMENT PRIMARY KEY,
    concern VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS moral (
    id INT AUTO_INCREMENT PRIMARY KEY,
    concern VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mortality (
    id INT AUTO_INCREMENT PRIMARY KEY,
    concern VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `2000_iq` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    question TEXT NOT NULL,
    remote_address VARCHAR(255),
    ip VARCHAR(45),
    dns VARCHAR(255),
    name VARCHAR(255),
    geo VARCHAR(255),
    national_id VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS module_installs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    installer_id VARCHAR(255) NOT NULL,
    national_id VARCHAR(100) NOT NULL,
    moral_rating VARCHAR(50) NOT NULL,
    iq INT NOT NULL,
    file_type VARCHAR(10) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    ip VARCHAR(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
