CREATE DATABASE IF NOT EXISTS green_durham_grass_and_herb;
USE green_durham_grass_and_herb;

CREATE TABLE IF NOT EXISTS ethical (
    id INT AUTO_INCREMENT PRIMARY KEY,
    concern VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS labor (
    id INT AUTO_INCREMENT PRIMARY KEY,
    concern VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS moral (
    id INT AUTO_INCREMENT PRIMARY KEY,
    concern VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mortality (
    id INT AUTO_INCREMENT PRIMARY KEY,
    concern VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
