CREATE DATABASE IF NOT EXISTS green_durham_grass_and_herb;
USE green_durham_grass_and_herb;

CREATE TABLE IF NOT EXISTS ethical (
    id INT AUTO_INCREMENT PRIMARY KEY,
    concern VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS labor (
    id INT AUTO_INCREMENT PRIMARY KEY,
    concern VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS moral (
    id INT AUTO_INCREMENT PRIMARY KEY,
    concern VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mortality (
    id INT AUTO_INCREMENT PRIMARY KEY,
    concern VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `2000_iq` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    question TEXT NOT NULL,
    remote_address VARCHAR(255),
    ip VARCHAR(45),
    dns VARCHAR(255),
    name VARCHAR(255),
    geo VARCHAR(255),
    national_id VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS listeners_east_coast (
    id INT AUTO_INCREMENT PRIMARY KEY,
    port INT DEFAULT 40002,
    message VARCHAR(255),
    remote_address VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS listeners_west_coast (
    id INT AUTO_INCREMENT PRIMARY KEY,
    port INT DEFAULT 40003,
    message VARCHAR(255),
    remote_address VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS listeners_wyoming (
    id INT AUTO_INCREMENT PRIMARY KEY,
    port INT DEFAULT 40005,
    message VARCHAR(255),
    remote_address VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS listeners_texas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    port INT DEFAULT 40007,
    message VARCHAR(255),
    remote_address VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS listeners_indiana (
    id INT AUTO_INCREMENT PRIMARY KEY,
    port INT DEFAULT 40009,
    message VARCHAR(255),
    remote_address VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS socialism (
    id INT AUTO_INCREMENT PRIMARY KEY,
    national_id VARCHAR(100) NOT NULL,
    ip VARCHAR(45),
    score INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
